# Generated by Django 6.0a1 on 2025-10-09 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_category_supplier_product_cost_product_stock_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta')], default='cash', max_length=10, verbose_name='Método de Pago'),
        ),
        migrations.CreateModel(
            name='CashDrawerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Hora de Apertura')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Cierre')),
                ('starting_balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fondo Inicial')),
                ('ending_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Saldo de Cierre')),
                ('notes', models.TextField(blank=True, verbose_name='Notas de Cierre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Cajero')),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='cash_drawer_session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='pos.cashdrawersession', verbose_name='Turno de Caja'),
            preserve_default=False,
        ),
    ]
