# Generated by Django 6.0a1 on 2025-10-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_alter_cashdrawersession_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='product_name',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
