# Generated by Django 6.0a1 on 2025-10-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_saleitem_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas de Venta'),
        ),
    ]
