# Generated by Django 6.0a1 on 2025-10-16 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_sale_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('dni_ruc', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='DNI/RUC')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sale',
            name='notes',
        ),
        migrations.AddField(
            model_name='product',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=5, verbose_name='Stock Mínimo de Alerta'),
        ),
        migrations.AddField(
            model_name='sale',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.client', verbose_name='Cliente Asociado'),
        ),
        migrations.CreateModel(
            name='SaleReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Devolución')),
                ('reason', models.TextField(verbose_name='Motivo de la Devolución')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto Reembolsado')),
                ('original_sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.sale', verbose_name='Venta Original')),
                ('returned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Procesado por')),
            ],
        ),
        migrations.CreateModel(
            name='SaleReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad Devuelta')),
                ('price_at_return', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio al Devolver')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.product', verbose_name='Producto Devuelto')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.salereturn', verbose_name='Solicitud de Devolución')),
            ],
        ),
    ]
