# Generated by Django 6.0a1 on 2025-10-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_client_remove_sale_notes_product_stock_minimo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='client',
        ),
        migrations.RemoveField(
            model_name='salereturn',
            name='original_sale',
        ),
        migrations.RemoveField(
            model_name='salereturn',
            name='returned_by',
        ),
        migrations.RemoveField(
            model_name='salereturnitem',
            name='return_request',
        ),
        migrations.RemoveField(
            model_name='salereturnitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_minimo',
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, help_text='Stock mínimo para disparar una alerta.', verbose_name='Umbral de Stock Bajo'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='SaleReturn',
        ),
        migrations.DeleteModel(
            name='SaleReturnItem',
        ),
    ]
