# Generated by Django 6.0a1 on 2025-10-16 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_client_sale_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Devolución')),
                ('motive', models.TextField(blank=True, verbose_name='Motivo')),
                ('total_refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto Reembolsado')),
                ('original_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='pos.sale', verbose_name='Venta Original')),
                ('returned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Procesado por')),
            ],
            options={
                'verbose_name': 'Devolución de Venta',
                'verbose_name_plural': 'Devoluciones de Ventas',
            },
        ),
        migrations.CreateModel(
            name='SaleReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad Devuelta')),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Reembolsado por Artículo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.product')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.salereturn')),
            ],
            options={
                'verbose_name': 'Artículo Devuelto',
                'verbose_name_plural': 'Artículos Devueltos',
            },
        ),
    ]
